export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.webp",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.webp",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "32",
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "3",
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "5",
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
  ],
}
