export default {
  products: [
    {
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.webp",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.webp",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Slim Shirt",
      category: "Paints",
      image: "/images/1.webp",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
  ],
}
